"""new model wordcup

Revision ID: be5545375605
Revises: 8f06466a5ea1
Create Date: 2019-11-23 20:17:43.176402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5545375605'
down_revision = '8f06466a5ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_cup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('champion', sa.String(length=100), nullable=True),
    sa.Column('runner_up', sa.String(length=100), nullable=True),
    sa.Column('third_place', sa.String(length=100), nullable=True),
    sa.Column('teams', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('goal_scored', sa.Integer(), nullable=True),
    sa.Column('avg_goals_per_game', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.drop_table('world_finals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_finals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('winners', sa.VARCHAR(length=100), nullable=True),
    sa.Column('final_score', sa.VARCHAR(length=100), nullable=True),
    sa.Column('runners_up', sa.INTEGER(), nullable=True),
    sa.Column('venue', sa.VARCHAR(length=100), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('attendance', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.drop_table('world_cup')
    # ### end Alembic commands ###
